#!/usr/bin/env python3
"""
Step 8 -- aggregate everything steps 1-7 wrote into a single machine-readable
manifest.json (per-file row counts, sha256, LF check) and a human-readable
provenance.md (pipeline diagram, seed table, verification summary), at the
root of the output directory.

Run this last, after 01-07 have all completed for a given --outdir.

Writes:
  <outdir>/manifest.json
  <outdir>/provenance.md
"""
import argparse
import glob
import os
import sys
import time

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from common import sha256_of, check_lf, count_rows, load_json, dump_json


def gather_files(outdir):
    patterns = [
        "01_positives.csv",
        "Parent_sequences/*.csv",
        "master_training_mix.csv",
        "MCCV/training_sets/*.csv",
        "MCCV/PRS-RRS/*.csv",
        "MCCV/random_controls/*.csv",
        "formats/ppiDCE_ppiBTEP/**/*.csv",
        "formats/ppiGPLM/**/*.csv",
    ]
    files = []
    for pat in patterns:
        files.extend(sorted(glob.glob(os.path.join(outdir, pat), recursive=True)))
    # de-dup while preserving order (glob patterns can overlap)
    seen = set()
    out = []
    for f in files:
        if f not in seen:
            seen.add(f)
            out.append(f)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--source-positive-file", required=True,
                     help="original input file path, for the provenance record")
    args = ap.parse_args()

    files = gather_files(args.outdir)
    file_records = []
    lf_failures = []
    for path in files:
        rel = os.path.relpath(path, args.outdir)
        rows = count_rows(path)
        lf_ok = check_lf(path)
        if not lf_ok:
            lf_failures.append(rel)
        file_records.append({
            "file": rel,
            "rows": rows,
            "sha256": sha256_of(path),
            "lf_only": lf_ok,
        })

    step_stats = {}
    for name, path in [
        ("positives", f"{args.outdir}/01_positives_stats.json"),
        ("random_pairs", f"{args.outdir}/Parent_sequences/random_pairs_stats.json"),
        ("random_substitution_sets", f"{args.outdir}/Parent_sequences/random_substitution_stats.json"),
        ("master_training_mix", f"{args.outdir}/master_training_mix_stats.json"),
        ("mccv", f"{args.outdir}/MCCV/mccv_stats.json"),
    ]:
        if os.path.exists(path):
            step_stats[name] = load_json(path)

    manifest = {
        "pipeline": "ppi-v3-dataset-pipeline",
        "source_positive_file": args.source_positive_file,
        "output_root": os.path.abspath(args.outdir),
        "n_files": len(file_records),
        "lf_check_failures": lf_failures,
        "step_stats": step_stats,
        "files": file_records,
    }
    dump_json(f"{args.outdir}/manifest.json", manifest)

    # -- human-readable provenance --
    pos_stats = step_stats.get("positives", {})
    rand_stats = step_stats.get("random_pairs", {})
    sub_stats = step_stats.get("random_substitution_sets", {})
    mix_stats = step_stats.get("master_training_mix", {})
    mccv_stats = step_stats.get("mccv", {})

    lines = []
    lines.append("# Provenance")
    lines.append("")
    lines.append(f"Generated by `scripts/08_make_manifest_and_provenance.py`.")
    lines.append("")
    lines.append("## 1. Pipeline chain")
    lines.append("")
    lines.append("```")
    lines.append(f"{os.path.basename(args.source_positive_file)}  (supplied)")
    lines.append("        |  01_make_positives.py")
    lines.append("        v")
    lines.append(f"01_positives.csv (+ Parent_sequences/positives.csv copy)   {pos_stats.get('n_positive_rows_written', '?')} rows "
                  f"({pos_stats.get('n_unique_unordered_pairs', '?')} unique pairs x2 orientations, "
                  f"{pos_stats.get('n_homodimers', '?')} homodimers x1)")
    lines.append(f"        |  02_make_random_pairs.py  (mode={rand_stats.get('mode', '?')}, seed 42, paralog-filtered)")
    lines.append("        v")
    dm_r = rand_stats.get('degree_match_pearson_r', '?')
    dm_r_str = f"{dm_r:.4f}" if isinstance(dm_r, float) else str(dm_r)
    lines.append(f"Parent_sequences/random_pairs.csv   {rand_stats.get('n_negative_rows_written', '?')} rows, "
                  f"degree-match r={dm_r_str}, "
                  f"{(rand_stats.get('paralog_filter') or {}).get('n_forbidden_paralog_shadow_pairs', '?')} paralog-shadow pairs excluded")
    lines.append("        |  03_make_random_substitution_sets.py  (seeds ps1/ps2/both)")
    lines.append("        v")
    lines.append("Parent_sequences/{ps1_random,ps2_random,both_random}.csv")
    lines.append("        |  04_make_master_mix.py  (seed 46)")
    lines.append("        v")
    lines.append(f"master_training_mix.csv                  {mix_stats.get('n_total_rows', '?')} rows, "
                  f"ratio {mix_stats.get('class_ratio_pos_to_neg', '?')}")
    lines.append("        |  05_make_mccv_replicates.py  (seeds 1000s-6000s + k; final shuffle + orientation/paralog checks)")
    lines.append("        v")
    lines.append(f"MCCV/   {mccv_stats.get('n_replicates', '?')} replicates, frac={mccv_stats.get('frac', '?')}")
    lines.append("        |  06_convert_format_ppiDCE_ppiBTEP.py")
    lines.append("        |  07_convert_format_ppiGPLM.py")
    lines.append("        v")
    lines.append("formats/{ppiDCE_ppiBTEP,ppiGPLM}/  (same tree, two encodings)")
    lines.append("```")
    lines.append("")
    lines.append("## 2. Seed table")
    lines.append("")
    lines.append("| stage | seed |")
    lines.append("|---|---|")
    lines.append("| in-distribution random pairs (step 2) | 42 |")
    lines.append("| ps1_random parent set (step 3) | 43 |")
    lines.append("| ps2_random parent set (step 3) | 44 |")
    lines.append("| both_random parent set (step 3) | 45 |")
    lines.append("| master mix shuffle (step 4) | 46 |")
    lines.append("| MCCV PRS selection, replicate k | 1000+k |")
    lines.append("| MCCV RRS selection, replicate k | 2000+k |")
    lines.append("| MCCV ps1-control selection, replicate k | 3000+k |")
    lines.append("| MCCV ps2-control selection, replicate k | 4000+k |")
    lines.append("| MCCV both-control selection, replicate k | 5000+k |")
    lines.append("| MCCV final training-set shuffle, replicate k | 6000+k |")
    lines.append("")
    lines.append("(Defaults shown; every seed is a CLI flag on its script, see README.md.)")
    lines.append("")
    lines.append("## 3. Verification")
    lines.append("")
    lines.append(f"- Files checked: **{len(file_records)}**")
    lines.append(f"- LF-only line endings: **{len(file_records) - len(lf_failures)}/{len(file_records)}** pass"
                  + (f" -- FAILURES: {lf_failures}" if lf_failures else ""))
    if mccv_stats:
        reps = mccv_stats.get("replicates", [])
        total_leak = sum(r["leak_check_pairs_present_in_depleted_set"] for r in reps)
        total_orient_leak = sum(r["orientation_leak_check"]["forward_A-B"] + r["orientation_leak_check"]["reverse_B-A"]
                                 for r in reps)
        total_rrs_paralog = sum(r.get("rrs_paralog_collisions", 0) for r in reps)
        lines.append(f"- MCCV leak check (held-out pairs re-found in their own depleted training set), "
                      f"summed over {mccv_stats.get('n_replicates', '?')} replicates: **{total_leak}**")
        lines.append(f"- MCCV orientation-depletion check (both A-B and B-A re-found in depleted set), "
                      f"summed over all replicates: **{total_orient_leak}**")
        lines.append(f"- MCCV RRS paralog-collision check (held-out random pairs matching a paralog-shadow "
                      f"of a positive pair), summed over all replicates: **{total_rrs_paralog}** "
                      f"(paralog filter: {'enabled, k=' + str(mccv_stats.get('paralog_k')) + ', threshold=' + str(mccv_stats.get('paralog_threshold')) if mccv_stats.get('paralog_filter_enabled') else 'disabled'})")
        lines.append(f"- RRS mode: **{mccv_stats.get('rrs_mode', rand_stats.get('mode', '?'))}**")
    if sub_stats:
        lines.append(f"- Random sequences generated (parent decoy sets): "
                      f"**{sub_stats.get('n_random_sequences_generated_total', '?')}**, "
                      f"collisions: {sub_stats.get('collision_retries', {})}")
    lines.append("")
    lines.append("## 4. Reproduce")
    lines.append("")
    lines.append("```bash")
    lines.append("cd scripts")
    lines.append(f"python 01_make_positives.py --input {args.source_positive_file} "
                  "--seq1-col <col> --seq2-col <col> --outdir <outdir>")
    lines.append("python 02_make_random_pairs.py --positives <outdir>/01_positives.csv --outdir <outdir>  "
                  "# add --mode out-of-distribution --proteome-csv <path> for OOD RRS")
    lines.append("python 03_make_random_substitution_sets.py --positives <outdir>/01_positives.csv --outdir <outdir>")
    lines.append("python 04_make_master_mix.py --outdir <outdir>")
    lines.append("python 05_make_mccv_replicates.py --outdir <outdir>")
    lines.append("python 06_convert_format_ppiDCE_ppiBTEP.py --outdir <outdir>")
    lines.append("python 07_convert_format_ppiGPLM.py --outdir <outdir>")
    lines.append(f"python 08_make_manifest_and_provenance.py --outdir <outdir> --source-positive-file {args.source_positive_file}")
    lines.append("```")
    lines.append("")
    lines.append("All steps are deterministic given their seeds; re-running reproduces byte-identical output "
                  "(verify with the sha256 column in manifest.json).")
    lines.append("")

    with open(f"{args.outdir}/provenance.md", "w", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"[08] wrote manifest.json ({len(file_records)} files) and provenance.md")
    if lf_failures:
        print(f"[08] WARNING: {len(lf_failures)} file(s) failed the LF-only check: {lf_failures}")


if __name__ == "__main__":
    main()
